# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-06 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=300)),
                ('upcoming_chapter', models.IntegerField(default=1)),
                ('url_pattern', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mangas', models.ManyToManyField(blank=True, related_name='subscribers', to='main.Manga')),
            ],
        ),
    ]
